version: '3.8'

volumes:
  postgres:
    name: postgres
    driver: local
    driver_opts:
      device: /var/tmp/docker/L0/postgresql
      o: bind
      type: none

services:
  nats-streaming:
    container_name: nats
    image: nats-streaming:linux
    ports:
      - "4222:4222"
      - "8222:8222"

  database:
    build: ./Postgres/
    image: db
    container_name: db
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  app:
    depends_on:
      - database
      - nats-streaming
    build: ./nats-service/
    image: app
    container_name: app
    ports:
      - "5000:5000"
    restart: always